version: "3"

services:
  php:
    image: webdevops/php-nginx:8.0-alpine
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public/
    volumes:
      - .:/app
      - ./install.sh:/opt/docker/provision/entrypoint.d/30-install.sh
    ports:
      - 8000:80
  node:
    image: node:16-alpine
    working_dir: /app
    user: node
    volumes:
      - .:/app
    command: sh -c 'npm install && npm run dev'
